### ISSUE TITLE
Could you provide the label2id files?

### ISSUE THREAD

**Issue by WrRan** [EiraZhang/LACO#7]
I have noticed LACO takes the labels as ``label0#label1#...#label53`` for the AAPD dataset and ``label0#...#label102`` for the RCV1-V2 dataset.
I can get close results to the paper on the AAPD dataset.
But on the RCV1-V2 dataset, the performance (mF1: 85.7) of the model trained from scratch with the _plcp_ strategy differs significantly from that in the paper (mF1: 88.4).
And I cannot use the provided checkpoint because there is no file to describe how to convert the original labels to the ids.

So could you provide the label2id files?

**Comment by EiraZhang** [comment]
schema_dict = {'ccat|Text': 'ccat', 'gcat|Text': 'gcat', 'mcat|Text': 'mcat', 'c15|Text': 'c15', 'ecat|Text': 'ecat',
     'm14|Text': 'm14',
     'c151|Text': 'c151', 'c152|Text': 'c152', 'gpol|Text': 'gpol', 'm13|Text': 'm13', 'c18|Text': 'c18',
     'm11|Text': 'm11',
     'm141|Text': 'm141', 'c181|Text': 'c181', 'e21|Text': 'e21', 'c17|Text': 'c17', 'c31|Text': 'c31',
     'gdip|Text': 'gdip',
     'c13|Text': 'c13', 'gspo|Text': 'gspo', 'gvio|Text': 'gvio', 'gcrim|Text': 'gcrim', 'c24|Text': 'c24',
     'm131|Text': 'm131',
     'e212|Text': 'e212', 'e12|Text': 'e12', 'm132|Text': 'm132', 'm12|Text': 'm12', 'c21|Text': 'c21',
     'c11|Text': 'c11',
     'c1511|Text': 'c1511', 'm143|Text': 'm143', 'e51|Text': 'e51', 'g15|Text': 'g15', 'c171|Text': 'c171',
     'gjob|Text': 'gjob',
     'e41|Text': 'e41', 'e211|Text': 'e211', 'c33|Text': 'c33', 'e512|Text': 'e512', 'm142|Text': 'm142',
     'c12|Text': 'c12',
     'c42|Text': 'c42', 'gvote|Text': 'gvote', 'c172|Text': 'c172', 'c41|Text': 'c41', 'c411|Text': 'c411',
     'gdef|Text': 'gdef',
     'gdis|Text': 'gdis', 'e11|Text': 'e11', 'g154|Text': 'g154', 'c14|Text': 'c14', 'c183|Text': 'c183',
     'c312|Text': 'c312',
     'e13|Text': 'e13', 'genv|Text': 'genv', 'c22|Text': 'c22', 'ghea|Text': 'ghea', 'c174|Text': 'c174',
     'e131|Text': 'e131',
     'gpro|Text': 'gpro', 'e71|Text': 'e71', 'c34|Text': 'c34', 'c182|Text': 'c182', 'g158|Text': 'g158',
     'c311|Text': 'c311',
     'gwea|Text': 'gwea', 'gent|Text': 'gent', 'g151|Text': 'g151', 'e511|Text': 'e511', 'grel|Text': 'grel',
     'godd|Text': 'godd',
     'c173|Text': 'c173', 'c23|Text': 'c23', 'e31|Text': 'e31', 'gsci|Text': 'gsci', 'g153|Text': 'g153',
     'e513|Text': 'e513',
     'e121|Text': 'e121', 'e14|Text': 'e14', 'e411|Text': 'e411', 'g155|Text': 'g155', 'g152|Text': 'g152',
     'c32|Text': 'c32',
     'g157|Text': 'g157', 'c16|Text': 'c16', 'gwelf|Text': 'gwelf', 'e311|Text': 'e311', 'c331|Text': 'c331',
     'e143|Text': 'e143',
     'c313|Text': 'c313', 'e132|Text': 'e132', 'gobit|Text': 'gobit', 'gtour|Text': 'gtour', 'e61|Text': 'e61',
     'e141|Text': 'e141',
     'gfas|Text': 'gfas', 'g156|Text': 'g156', 'e142|Text': 'e142', 'e313|Text': 'e313', 'e312|Text': 'e312',
     'g159|Text': 'g159', 'gmil|Text': 'gmil'}

**Comment by WrRan** [comment]
Thanks for your timely reply.
I put the final mapping file here for the convenience of those who need it.
```python
{
    "CCAT": 0,
    "GCAT": 1,
    "MCAT": 2,
    "C15": 3,
    "ECAT": 4,
    "M14": 5,
    "C151": 6,
    "C152": 7,
    "GPOL": 8,
    "M13": 9,
    "C18": 10,
    "M11": 11,
    "M141": 12,
    "C181": 13,
    "E21": 14,
    "C17": 15,
    "C31": 16,
    "GDIP": 17,
    "C13": 18,
    "GSPO": 19,
    "GVIO": 20,
    "GCRIM": 21,
    "C24": 22,
    "M131": 23,
    "E212": 24,
    "E12": 25,
    "M132": 26,
    "M12": 27,
    "C21": 28,
    "C11": 29,
    "C1511": 30,
    "M143": 31,
    "E51": 32,
    "G15": 33,
    "C171": 34,
    "GJOB": 35,
    "E41": 36,
    "E211": 37,
    "C33": 38,
    "E512": 39,
    "M142": 40,
    "C12": 41,
    "C42": 42,
    "GVOTE": 43,
    "C172": 44,
    "C41": 45,
    "C411": 46,
    "GDEF": 47,
    "GDIS": 48,
    "E11": 49,
    "G154": 50,
    "C14": 51,
    "C183": 52,
    "C312": 53,
    "E13": 54,
    "GENV": 55,
    "C22": 56,
    "GHEA": 57,
    "C174": 58,
    "E131": 59,
    "GPRO": 60,
    "E71": 61,
    "C34": 62,
    "C182": 63,
    "G158": 64,
    "C311": 65,
    "GWEA": 66,
    "GENT": 67,
    "G151": 68,
    "E511": 69,
    "GREL": 70,
    "GODD": 71,
    "C173": 72,
    "C23": 73,
    "E31": 74,
    "GSCI": 75,
    "G153": 76,
    "E513": 77,
    "E121": 78,
    "E14": 79,
    "E411": 80,
    "G155": 81,
    "G152": 82,
    "C32": 83,
    "G157": 84,
    "C16": 85,
    "GWELF": 86,
    "E311": 87,
    "C331": 88,
    "E143": 89,
    "C313": 90,
    "E132": 91,
    "GOBIT": 92,
    "GTOUR": 93,
    "E61": 94,
    "E141": 95,
    "GFAS": 96,
    "G156": 97,
    "E142": 98,
    "E313": 99,
    "E312": 100,
    "G159": 101,
    "GMIL": 102
}
```

**Comment by amal-spec** [comment]
Can you provide data preprocessing code？thanks
